[build]
base = "."  # The base directory is the client folder
command = "npm install && npm run build"
publish = "build"  # Output of the build command, where Netlify will serve files from

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
